[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[project]
name = "gidgethub"
authors = [{name = "Brett Cannon", email = "brett@python.org"}]
maintainers = [{name = "Mariatta", email = "mariatta@mariatta.ca"}]
dependencies = [
    "uritemplate>=3.0.1",
    "PyJWT[crypto]>=2.4.0",
    "typing_extensions>=4.0.0",
]
requires-python = ">=3.10"
license = "Apache-2.0 AND MIT"
license-files = ["LICENSE", "Third-Party-Notices.md"]
keywords = ["github", "sans-io", "async"]
readme = "README.rst"
classifiers = [
    "Intended Audience :: Developers",
    "Development Status :: 6 - Mature",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
]
description = "An async GitHub API library"
dynamic = ["version"]

[project.urls]
Documentation = "https://gidgethub.readthedocs.io"
Repository = "https://github.com/gidgethub/gidgethub"

[project.optional-dependencies]
aiohttp = ["aiohttp"]
tornado = ["tornado"]
httpx = ["httpx2"]  # For backwards-compatibility.
httpx2 = ["httpx2"]


[dependency-groups]
test = ["importlib-resources", "pytest>=5.4.1", "pytest-asyncio", "pytest-tornasync",
        "pytest-cov", "pytest-xdist", "coverage[toml]>=5.0.3"]
format = ["black>=26.5.1"]
type-check = ["pyrefly>=1.2.0", "mypy>=2.3.1", {include-group = "test"}]
code-check = ["ruff>=0.16.6"]
lint = [{include-group = "code-check"}, {include-group = "format"}, {include-group = "type-check"}]
doc = ["sphinx>=4.0.0", "sphinx-rtd-theme>=0.5.2"]
dev = ["nox", {include-group = "test"}, {include-group = "lint"}, {include-group = "doc"}]

[tool.pdm.version]
source = "file"
path = "gidgethub/__init__.py"

[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests"]

[tool.pyrefly]
project-excludes = ["noxfile.py"]
coverage = {excludes = ["noxfile.py", "tests/**"]}

[tool.coverage.run]
branch = true

[tool.coverage.report]
fail_under = 100
